### ISSUE TITLE
Highlighting of Racket in source blocks

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [wallyqs/ob-racket#1]
Great package here, but I have a question.

I guess highlighting is not the job of ob-racket, but an appropriate color theme, which has the colors for highlighting Racket code inside org source blocks.

Nevertheless I want to ask, because you might know: Do you know some good color themes which do syntax highlighting for Racket in org source blocks? I would like to use org-babel and ob-racket more, but without highlighting, it is not so much fun. I only get color for matching parentheses, because that is a more general setting.

**Comment by ZelphirKaltstahl** [comment]
I seem to have figured out how to get normal highlighting in org mode source blocks:

I needed to add the following to my `init.el`.

    (setq org-src-fontify-natively t)

**Comment by wallyqs** [comment]
@ZelphirKaltstahl yes that should do it, then would just use a code block using `lisp` as the language so that it syntax highlighting is enabled:

```
#+BEGIN_SRC lisp

#+END_SRC
```
